---

openvpn_enabled: yes                                # The role is enabled

openvpn_etcdir: /etc/openvpn
openvpn_easyrsa2dir: "{{openvpn_etcdir}}/easy-rsa2"
openvpn_keydir: "{{openvpn_etcdir}}/keys"
openvpn_opensslcnf: "openssl-1.0.0.cnf"

# Default settings (See OpenVPN documentation)
openvpn_host: "{{inventory_hostname}}"              # The server address
openvpn_port: 1194
openvpn_proto: tcp
openvpn_dev: tap
openvpn_server: 10.8.8.0 255.255.255.0              # Set empty for skip
openvpn_max_clients: 100
openvpn_log: /var/log/openvpn.log                   # Log's directory
openvpn_keepalive: "10 120"
openvpn_ifconfig_pool_persist: ipp.txt
openvpn_comp_lzo: yes                               # Enable compression
openvpn_status: openvpn-status.log
openvpn_verb: 3
openvpn_user: openvpn
openvpn_group: openvpn
openvpn_resolv_retry: infinite
openvpn_client_to_client: yes
openvpn_server_options: []                          # Additional server options
                                                    # openvpn_server_options:
                                                    # - dev-node MyTap
                                                    # - client-to-client
openvpn_client_options: []                          # Additional client options
                                                    # openvpn_client_options:
                                                    # - dev-node MyTap
                                                    # - client-to-client

openvpn_key_country: US
openvpn_key_province: CA
openvpn_key_city: SanFrancisco
openvpn_key_org: Fort-Funston
openvpn_key_email: me@myhost.mydomain
openvpn_key_size: 1024

openvpn_clients: [client]                         # Make clients certificate
openvpn_clients_revoke: []                        # Revoke clients certificates
